service: sms-notification
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

functions:
  send_sms:
    handler: handler.send
    role: ${ssm:${self:custom.stage}-sms-iam-role}
    environment: 
      MESSAGE_SMS_API_KEY: ${ssm:${self:custom.stage}-message-sms-api-key}
      SMS_PHONE_FROM: ${ssm:${self:custom.stage}-sms-phone-from}
      SMS_PHONE_TO: ${ssm:${self:custom.stage}-sms-phone-to}
    events:
      - sqs: 
          name: ${ssm:${self:custom.stage}-sms-sqs}

custom:
  stage: ${opt:stage, self:provider.stage}