service: bookings-consumer
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

functions:
  stream_listener:
    handler: handler.listen
    role: ${ssm:${self:custom.stage}-bookings-stream-consumer-iam-role}
    environment:
      SNS_NOTIFICATIONS_TOPIC: ${ssm:${self:custom.stage}-notifications-topic}
    events:
      - stream:
          name: ${ssm:${self:custom.stage}-dynamodb-bookings-stream}
